In [1]:
import numpy as np;

In [2]:
myarr=np.array([[3,6,37,7]],np.int64)

In [3]:
myarr.shape

(1, 4)

In [4]:
myarr.dtype

dtype('int64')

In [6]:
listarray=np.array([[1,2,3],[4,5,6],[7,8,9]])
listarray

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
listarray.shape

(3, 3)

In [8]:
listarray.size

9

In [9]:
zeros=np.zeros((2,5))

In [10]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [11]:
rng=np.arange(15)

In [12]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [13]:
lspace=np.linspace(1,5,12)

In [14]:
lspace

array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])

In [18]:
emp=np.empty((4,6))

In [22]:
emp

array([[6.23042070e-307, 3.56043053e-307, 1.37961641e-306,
        8.90071135e-308, 8.01097889e-307, 1.78020169e-306],
       [7.56601165e-307, 1.02359984e-306, 1.33510679e-306,
        2.22522597e-306, 1.33511018e-306, 6.23057689e-307],
       [1.86921279e-306, 8.90098127e-307, 1.78020848e-306,
        1.60219035e-306, 1.42418172e-306, 8.06609645e-308],
       [6.89810244e-307, 1.22387550e-307, 2.22522596e-306,
        8.34423917e-308, 1.11261162e-306, 1.78021527e-306]])

In [23]:
emp_like=np.empty_like(lspace)
emp_like

array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])

In [24]:
ide=np.identity(45)
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [28]:
arr=myarr.reshape(4,1)
arr

array([[ 3],
       [ 6],
       [37],
       [ 7]], dtype=int64)

In [30]:
arr=arr.ravel()
arr

array([ 3,  6, 37,  7], dtype=int64)

In [32]:
arr.shape

(4,)

In [34]:
x=[[1,2,3],[4,5,6],[7,8,9]]
useAbleArray=np.array(x)
useAbleArray

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [35]:
useAbleArray.sum(axis=0)

array([12, 15, 18])

In [36]:
useAbleArray.sum(axis=1)

array([ 6, 15, 24])

In [37]:
useAbleArray.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [38]:
arr.flat

In [40]:
for item in useAbleArray.flat:
    print(item)

1
2
3
4
5
6
7
8
9


In [41]:
useAbleArray.ndim

2

In [42]:
useAbleArray.nbytes

36

In [45]:
one=np.array([1,3,4,634,2])
# one.argmax()
# one.argmin()
one.argsort()

array([0, 4, 1, 2, 3], dtype=int64)

In [46]:
np.sqrt(useAbleArray)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [47]:
useAbleArray.sum()

45

In [48]:
useAbleArray.max()

9

In [49]:
useAbleArray.min()

1

In [50]:
np.where(useAbleArray>5)

(array([1, 2, 2, 2], dtype=int64), array([2, 0, 1, 2], dtype=int64))

In [51]:
np.count_nonzero(useAbleArray)

9

In [52]:
np.nonzero(useAbleArray)

(array([0, 0, 0, 1, 1, 1, 2, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 2, 0, 1, 2], dtype=int64))