In [1]:
import numpy as np

In [5]:
arr1=np.random.random(12).reshape(4,3)*100
arr1

array([[72.93086848,  1.89056226, 15.43099786],
       [78.14195307, 73.52689765, 18.40761652],
       [25.26857751, 14.12705864, 57.10986771],
       [78.29364654, 47.45892567, 10.53189537]])

In [6]:
arr1[[0,2,3]]

array([[72.93086848,  1.89056226, 15.43099786],
       [25.26857751, 14.12705864, 57.10986771],
       [78.29364654, 47.45892567, 10.53189537]])

In [8]:
arr2=np.random.randint(1,100,24).reshape(6,4)
arr2

array([[47, 39, 76,  5],
       [93,  8,  2, 79],
       [35, 22, 62, 53],
       [27, 51, 45, 20],
       [34, 65, 32, 90],
       [74, 88, 66,  8]])

In [9]:
arr2[arr2>50]

array([76, 93, 79, 62, 53, 51, 65, 90, 74, 88, 66])

In [10]:
actual=np.random.randint(1,50,25)
predicted=np.random.randint(1,50,25)


In [11]:
actual

array([15, 20, 19, 34, 24, 19, 19, 30, 37, 46,  2, 23, 38, 38, 20, 39,  2,
       14, 37, 46,  6, 32,  9, 26, 13])

In [12]:
predicted

array([29, 41, 36,  1, 15, 47, 13, 47, 36, 49, 35, 42, 11, 49, 32,  4, 13,
       32, 22,  4, 12, 33, 13,  6, 10])

In [14]:
def mse(actual,predicted):
    return np.mean((actual-predicted)**2)
mse(actual,predicted)

391.2

In [15]:
arr3=np.array([1,2,3,4,np.nan,6])
arr3

array([ 1.,  2.,  3.,  4., nan,  6.])

In [17]:
np.isnan(arr3)

array([False, False, False, False,  True, False])