In [1]:
import numpy as np

In [2]:
a=np.array([10,20,30])
a

array([10, 20, 30])

In [3]:
b=np.array([[1,2,3],[4,5,6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
np.arange(1,11).reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [7]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [8]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [9]:
np.random.random((3,4))

array([[0.83671762, 0.59644441, 0.22257879, 0.51860253],
       [0.27803372, 0.65465894, 0.9283917 , 0.24635459],
       [0.74491286, 0.4943946 , 0.65696417, 0.97208683]])

In [10]:
np.linspace(-10,10,10)

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [11]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [12]:
a1=np.arange(10)
a2=np.arange(12,dtype=float).reshape(3,4)
a3=np.arange(8).reshape(2,2,2)

In [17]:
print("THIS IS a1->",a1)
print("THIS IS a2->",a2)
print("THIS IS a3->",a3)

THIS IS a1-> [0 1 2 3 4 5 6 7 8 9]
THIS IS a2-> [[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
THIS IS a3-> [[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [18]:
print("THE DIMENSION OF a1->",a1.ndim)
print("THE DIMENSION OF a2->",a2.ndim)
print("THE DIMENSION OF a3->",a3.ndim)

THE DIMENSION OF a1-> 1
THE DIMENSION OF a2-> 2
THE DIMENSION OF a3-> 3


In [19]:
print("THE SHAPE OF a1->",a1.shape)
print("THE SHAPE OF a2->",a2.shape)
print("THE SHAPE OF a3->",a3.shape)

THE SHAPE OF a1-> (10,)
THE SHAPE OF a2-> (3, 4)
THE SHAPE OF a3-> (2, 2, 2)


In [22]:
print("THE SIZE OF a1->",a1.size)
print("THE SIZE OF a2->",a2.size)
print("THE SIZE OF a3->",a3.size)

THE SIZE OF a1-> 10
THE SIZE OF a2-> 12
THE SIZE OF a3-> 8


In [23]:
print("THE ITEMSIZE OF a1->",a1.itemsize)
print("THE ITEMSIZE OF a2->",a2.itemsize)
print("THE ITEMSIZE OF a3->",a3.itemsize)

THE ITEMSIZE OF a1-> 4
THE ITEMSIZE OF a2-> 8
THE ITEMSIZE OF a3-> 4


In [24]:
print("THE DATATYPE OF a1->",a1.dtype)
print("THE DATATYPE OF a2->",a2.dtype)
print("THE DATATYPE OF a3->",a3.dtype)

THE DATATYPE OF a1-> int32
THE DATATYPE OF a2-> float64
THE DATATYPE OF a3-> int32


In [29]:
a3.astype(np.int64)
print("THIS IS UPDATED DATA TYPE->",a3.dtype)

THIS IS UPDATED DATA TYPE-> int32


In [30]:
a1*2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [32]:
a2>10

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True]])

In [33]:
a4=np.random.random((3,3))
a4=np.round(a4*100)
a4

array([[ 3., 82., 55.],
       [42., 45., 60.],
       [49., 14., 94.]])

In [34]:

print("THE MAXIMUM OF a4 is->",np.max(a4))
print("THE MINIMUM OF a4 is->",np.min(a4))
print("THE SUM OF a4 is->",np.sum(a4))
print("THE PRODUCT OF a4 IS->",np.prod(a4))

THE MAXIMUM OF a4 is-> 94.0
THE MINIMUM OF a4 is-> 3.0
THE SUM OF a4 is-> 444.0
THE PRODUCT OF a4 IS-> 98937930168000.0


In [36]:
#0->col,1->row
np.max(a4,axis=1) 

array([82., 60., 94.])

In [37]:
print("THIS WILL BE MEAN OF a4->",np.mean(a4))
print("THIS WILL BE MEDIAN OF a4->",np.median(a4))
print("THIS WILL BE STANDARD DEVATION OF a4->",np.std(a4))

THIS WILL BE MEAN OF a4-> 49.333333333333336
THIS WILL BE MEDIAN OF a4-> 49.0
THIS WILL BE STANDARD DEVATION OF a4-> 27.23559762108733


In [38]:
print("THE LOG OF a4->",np.log2(a4))
print("THE EXPONENT OF a4->",np.exp(a4))

THE LOG OF a4-> [[1.5849625  6.357552   5.78135971]
 [5.39231742 5.4918531  5.9068906 ]
 [5.61470984 3.80735492 6.55458885]]
THE EXPONENT OF a4-> [[2.00855369e+01 4.09399696e+35 7.69478527e+23]
 [1.73927494e+18 3.49342711e+19 1.14200739e+26]
 [1.90734657e+21 1.20260428e+06 6.66317622e+40]]


In [39]:
a5=np.arange(10)
a6=np.arange(12).reshape(3,4)
a7=np.arange(8).reshape(2,2,2)

print("THIS IS ARRAY a5->",a5)
print("THIS IS ARRAY a6->",a6)
print("THIS IS ARRAY a7->",a7)

THIS IS ARRAY a5-> [0 1 2 3 4 5 6 7 8 9]
THIS IS ARRAY a6-> [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
THIS IS ARRAY a7-> [[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [44]:
a6[2,3]


11

In [45]:
a7[1,1,0]

6

In [47]:
a5[2:6]

array([2, 3, 4, 5])

In [48]:
a6[0,:]

array([0, 1, 2, 3])

In [49]:
a6[:,2]

array([ 2,  6, 10])

In [51]:
a6[1:,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [53]:
for i in a1:
    print("ITEM IN a1 ARRAY->",i)

ITEM IN a1 ARRAY-> 0
ITEM IN a1 ARRAY-> 1
ITEM IN a1 ARRAY-> 2
ITEM IN a1 ARRAY-> 3
ITEM IN a1 ARRAY-> 4
ITEM IN a1 ARRAY-> 5
ITEM IN a1 ARRAY-> 6
ITEM IN a1 ARRAY-> 7
ITEM IN a1 ARRAY-> 8
ITEM IN a1 ARRAY-> 9


In [54]:
for i in a2:
    print("ITEM IN a2 ARRAY->",i)

ITEM IN a2 ARRAY-> [0. 1. 2. 3.]
ITEM IN a2 ARRAY-> [4. 5. 6. 7.]
ITEM IN a2 ARRAY-> [ 8.  9. 10. 11.]


In [55]:
for i in a3:
    print("ITEM IN a3 ARRAY->",i)

ITEM IN a3 ARRAY-> [[0 1]
 [2 3]]
ITEM IN a3 ARRAY-> [[4 5]
 [6 7]]


In [56]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [57]:
np.transpose(a3)

array([[[0, 4],
        [2, 6]],

       [[1, 5],
        [3, 7]]])

In [58]:
a3.T

array([[[0, 4],
        [2, 6]],

       [[1, 5],
        [3, 7]]])

In [59]:
a3.ravel()

array([0, 1, 2, 3, 4, 5, 6, 7])

In [62]:
arr1=np.arange(12).reshape(3,4)
arr2=np.arange(12,24).reshape(3,4)
print("THIS IS ARRAY1->",arr1)
print("THIS IS ARRAY2->",arr2)

THIS IS ARRAY1-> [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
THIS IS ARRAY2-> [[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [63]:
np.hstack((arr1,arr2))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [65]:
np.vstack((arr1,arr2))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [67]:
np.hsplit(arr1,2)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [68]:
np.vsplit(arr1,3)

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]